### ISSUE TITLE
制作了一个同步服务的docker镜像方便私有化部署

### ISSUE THREAD

**Issue by Aliang-code** [electerm/electerm#3659]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

[fork from electerm-sync-server-java](https://github.com/Aliang-code/electerm-sync-server-java-docker)
docker compose:
```
version: '3'
services:
  electerm-sync-server:
    restart: on-failure
    image: aliangbaby/electerm-sync-server-java
    ports:
      #指定对外端口
      - 47837:7837
    volumes:
      #指定配置存储路径
      - /path/for/config:/app/config
    environment:
      #设置密钥，可以使用openssl rand -base64 32生成
      - JWT_SECRET=ChangeIt
      #用户名，可以多个，英文逗号分割
      - JWT_USERS=username
```
然后在设置同步中选择custom填入容器外网地址（http://xxx:47837/api/sync ） 和JWT信息
